package org.example.cayenne.persistent.auto;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;

import org.apache.cayenne.BaseDataObject;
import org.apache.cayenne.exp.property.PropertyFactory;
import org.apache.cayenne.exp.property.StringProperty;

/**
 * Class _Book was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Book extends BaseDataObject {

    private static final long serialVersionUID = 1L;

    public static final String ID_PK_COLUMN = "ID";

    public static final StringProperty<String> AUTHOR = PropertyFactory.createString("author", String.class);
    public static final StringProperty<String> ISBN = PropertyFactory.createString("isbn", String.class);
    public static final StringProperty<String> NAME = PropertyFactory.createString("name", String.class);

    protected String author;
    protected String isbn;
    protected String name;


    public void setAuthor(String author) {
        beforePropertyWrite("author", this.author, author);
        this.author = author;
    }

    public String getAuthor() {
        beforePropertyRead("author");
        return this.author;
    }

    public void setIsbn(String isbn) {
        beforePropertyWrite("isbn", this.isbn, isbn);
        this.isbn = isbn;
    }

    public String getIsbn() {
        beforePropertyRead("isbn");
        return this.isbn;
    }

    public void setName(String name) {
        beforePropertyWrite("name", this.name, name);
        this.name = name;
    }

    public String getName() {
        beforePropertyRead("name");
        return this.name;
    }

    @Override
    public Object readPropertyDirectly(String propName) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch(propName) {
            case "author":
                return this.author;
            case "isbn":
                return this.isbn;
            case "name":
                return this.name;
            default:
                return super.readPropertyDirectly(propName);
        }
    }

    @Override
    public void writePropertyDirectly(String propName, Object val) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch (propName) {
            case "author":
                this.author = (String)val;
                break;
            case "isbn":
                this.isbn = (String)val;
                break;
            case "name":
                this.name = (String)val;
                break;
            default:
                super.writePropertyDirectly(propName, val);
        }
    }

    private void writeObject(ObjectOutputStream out) throws IOException {
        writeSerialized(out);
    }

    private void readObject(ObjectInputStream in) throws IOException, ClassNotFoundException {
        readSerialized(in);
    }

    @Override
    protected void writeState(ObjectOutputStream out) throws IOException {
        super.writeState(out);
        out.writeObject(this.author);
        out.writeObject(this.isbn);
        out.writeObject(this.name);
    }

    @Override
    protected void readState(ObjectInputStream in) throws IOException, ClassNotFoundException {
        super.readState(in);
        this.author = (String)in.readObject();
        this.isbn = (String)in.readObject();
        this.name = (String)in.readObject();
    }

}
